### ISSUE TITLE
Fog not recognized 

### ISSUE THREAD

**Issue by christoros** [sonowz/wallpaper-engine-live-weather#1]
I get an error when it is foggy outside. I did add something into the code so the line 75 might be incorrect, but it should be unrelated to this problem. 
log:
`DEBUG:root:Start main loop
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.openweathermap.org:443
DEBUG:urllib3.connectionpool:https://api.openweathermap.org:443 "GET /data/2.5/weather?q=REMOVED LOCATION HTTP/1.1" 200 461
DEBUG:root:{'id': 741, 'main': 'Fog', 'description': 'fog', 'icon': '50d'}
ERROR:root:main loop error
Traceback (most recent call last):
  File "main.py", line 75, in main_loop
    weather_raw = get_weather(CONFIG["api_key"], CONFIG["city"], CONFIG["country"])
KeyError: 'Fog'
DEBUG:root:End main loop`

**Comment by sonowz** [comment]
Thank you for reporting the issue!
It turns out that I missed some weathers on the API list, so I added them.

Since you are already using the program, just add weather bindings in the `config.json` would fix the error:
```json
  "weather_bindings": {
        "Clear": "sunny",
        "Atmosphere": "sunny",
        "Clouds": "sunny",
        "Drizzle": "sunny",
        "Rain": "rainy",
        "Thunderstorm": "rainy",
        "Snow": "rainy",
        "Mist": "rainy",
        "Smoke": "rainy",
        "Haze": "rainy",
        "Dust": "rainy",
        "Fog": "rainy",
        "Sand": "rainy",
        "Ash": "rainy",
        "Squall": "rainy",
        "Tornado": "rainy"
    }
```
